# Example configuration file for Terraform Collection Pipeline
# List of Git repositories to collect .tf files from
# Only SSH URLs are supported (git@github.com:org/repo.git format)

repositories:
  - git@github.com:hashicorp/terraform-aws-modules.git
  - git@github.com:terraform-aws-modules/terraform-aws-vpc.git
  - git@github.com:terraform-aws-modules/terraform-aws-security-group.git
  
# Optional: Configure rate limiting between clones (seconds)
# rate_limit: 0.1

# Configuration for automatic repository discovery from Bitbucket
# Run 'python repos.py' to generate repos.yaml from these settings
bitbucket:
  server:
    url: "https://bitbucket.example.com"
    username: "your-username"
    password: "your-app-password"  # or set BITBUCKET_SERVER_PASSWORD env var
    projects:
      - name: "TERRAFORM"
        repo_pattern: "terraform-.*"
      - name: "INFRA" 
        repo_pattern: ".*-terraform"
  cloud:
    username: "your-username"
    app_password: "your-app-password"  # or set BITBUCKET_CLOUD_APP_PASSWORD env var
    workspaces:
      - name: "my-workspace"
        repo_pattern: "terraform-.*"
      - name: "infra-workspace"
        repo_pattern: ".*-infrastructure"